server:
  port: 8082
  servlet:
    context-path: /DieIndustry
  
spring:
  profiles:
    active:
    - dev
  main:
    allow-circular-references: true
  datasource:
    username: postgres
    password: yamamato 
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=die_industries
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 10000
      max-lifetime: 1000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  session:
    store-type: jdbc
  security: 
    user:
      name: shree
      password: shree
  mail:
    host: smtp.gmail.com
    port: 587
    username: dieindustry@gmail.com
    password: widaikitzhylchps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO

bypassFlag: false



