server:
  port: 8083

management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  configs:
    default:
      register-health-indicator: true
      event-consumer-buffer-size: 10
      failure-rate-threshold: 50
      minimum-number-of-calls: 5
      automatic-transition-from-open-to-half-open-enabled: true
      wait-duration-in-open-state: 5s
      permitted-number-of-calls-in-half-open-state: 3
      sliding-window-size: 10
      sliding-window-type: count-based
      slow-call-duration-threshold: 5000
      slow-call-rate-threshold: 50
  instances:
    orderCircuitBreaker:
      baseConfig: default

spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order-service
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/orderFallback
          predicates:
            - Path=/order/**
        - id: payment
          uri: http://payment-service
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/paymentFallback
          predicates:
            - Path=/payment/**
        - id: jwtauth
          uri: http://security-jwt
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/jwtAuthServiceFallback
          predicates:
            - Path=/jwtauth/**
