server:
  port: 8083
  forward-headers-strategy: framework

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  configs:
    default:
      register-health-indicator: true
      failure-rate-threshold: 50
      minimum-number-of-calls: 5
      wait-duration-in-open-state: 5s
      sliding-window-size: 10
  instances:
    orderCircuitBreaker:
      base-config: default

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-service:7080/realms/prototype-realm/protocol/openid-connect/certs
          audiences:
            - account
            - spring-boot-app
      client:
        registration:
          my-keycloak:
            provider: my-keycloak
            client-id: spring-boot-app
            client-secret: VqNrk384VYN2qdGKF1bk2tjv3uFfDdgE
            scope:
              - openid
              - profile
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          my-keycloak:
            issuer-uri: http://keycloak-service:7080/realms/prototype-realm

  cloud:
    gateway:
      server:
        webflux:
          forwarded:
            enabled: true
          routes:
            - id: order
              uri: http://order-service
              predicates:
                - Path=/order/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - TokenRelay=
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
                    fallbackUri: forward:/orderFallback
            - id: payment
              uri: http://payment-service
              predicates:
                - Path=/payment/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - TokenRelay=
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
                    fallbackUri: forward:/paymentFallback
            - id: jwtauth
              uri: http://security-jwt
              predicates:
                - Path=/jwtauth/**
              filters:
                - TokenRelay=
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
                    fallbackUri: forward:/jwtAuthServiceFallback

