spring:
  zipkin:
    base-url: http://localhost:9411
    
    
logging:
  level:
    root:  INFO
  pattern:
    file: "%-5level %d{HH:mm:ss.SSS} [%thread] [${spring.zipkin.service.name: ${spring.application.name:}},TraceId: %X{traceId:-}, SpanId: %X{spanId:-}] %logger{36}  : %msg%n"
    console: "%-5level %d{HH:mm:ss.SSS} [%thread] [${spring.zipkin.service.name: ${spring.application.name:}},TraceId: %X{traceId:-}, SpanId: %X{spanId:-}] %logger{36}  : %msg%n"
  file:
    name: logs/logfile.log
  